#!/bin/bash

reset="\033[0m"
red="\033[1;31m"
green="\033[1;32m"
erase_line="\r\033[2K"

IFS=""
commands=(
    "cargo fmt --check --manifest-path src-tauri/Cargo.toml"
    "npx eslint . --color"
)
steps=(
    "cargo fmt"
    "eslint"
)

for i in "${!commands[@]}"; do
    printf "[$((i + 1))/${#commands[@]}] ${green}Validating$reset ${steps[$i]}"
    if ! output=$(eval "${commands[$i]}"); then
        printf "$erase_line[$((i + 1))/${#commands[@]}] ${red}Failed$reset ${steps[$i]}\n"
        printf "$output"
        exit 1
    fi
    printf "$erase_line[$((i + 1))/${#commands[@]}] ${green}Validated$reset ${steps[$i]}\n"
done
